name: Publish Python Package

on:
  push:
    tags:
      - "v0.1.0

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
      
    - name: Install build dependencies
      run: python -m pip install --upgrade pip setuptools wheel build twine
      
    - name: Build package
      run: python -m build
      
    - name: Verify package
      run: twine check dist/*
      
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}